### ISSUE TITLE
The progress of making dataset is too slow

### ISSUE THREAD

**Issue by ElegantLin** [AIprogrammer/AdvMix#2]
I downloaded the raw images of COCO 2017 validation and MPII. The remaining time of executing `make_dataset.sh` is very long, like 1000+ hrs. Is it correct?

**Comment by annopackage** [comment]
Hi, the speed should not be that slow. You can change "batch_size" and "num_workers" while running the scripts.

**Comment by ElegantLin** [comment]
Sure. Thanks!
